name: CI

env:
  container_registry: azureapiflask.azurecr.io/azureapi/flask:latest
  resourceGroup: labthree
  appName: azureapiflask2020

# Controls when the action will run. Triggers the workflow on push or pull request events but only for the master branch
# on - push: any time code pushed to branch then trigger workflow
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on azureapiflask.azurecr.io/azureapi/flask:latest
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    -  uses: Azure/login@v1
       with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        login-server: ${{ env.container_registry }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Azure CLI Action
      uses: Azure/cli@v1.0.0
      with:
        inlineScripts: az appservice plan create -g $${{ env.resourceGroup }} -n azureapiplan --is-linux

    - name: Azure CLI Action
      uses: Azure/cli@v1.0.0
      with: az webapp create -g ${{ env.resourceGroup }} -p azureapiplan -n ${{ env.appName }} --runtime "$pytthon|3.8"
    
    - name: Azure WebApp
      users: Azure/webapps-deploy@v2
      with:
        app-name: azureapiflask2020
        images:
